---
services:

  prometheus_server:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus_server
    restart: unless-stopped
    user: "82" # uid of host system docker user
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_server/prometheus_data:/prometheus
      - ./prometheus_server/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "82" # uid of host system docker user
    depends_on:
      - prometheus_server
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/data:/var/lib/grafana

  prometheus_exporter:
    build: .
    container_name: prometheus_exporter
    restart: unless-stopped
    user: "82" # uid of host system docker user
    ports:
      - 8000:8000

  nginx:
    image: docker.io/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/grafana.conf:/etc/nginx/conf.d/default.conf
