{
 "title": "Flesh Recycler",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Electrical Wattage Used for Recycling Flesh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "myproject_mycategory_myservice_watts",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Flesh Recycler Overdrive ON(1) or OFF(0)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myproject_mycategory_myservice_flesh_recycler_overdrive_state",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Flesh Recycling Motors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "myproject_mycategory_myservice_active_motors",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}